FROM node:20-alpine

WORKDIR /app

# Copy package.json + lock file
COPY package*.json ./

# Install all dependencies (including dev)
RUN npm install

# Copy entire project
COPY . .

# Expose dev port
EXPOSE 3000

# Run Next.js dev server
CMD ["npm", "run", "dev"]
